resilience4j.circuitbreaker:
    instances:
      GuestMS:
        register-health-indicator: true
        failure-rate-threshold: 50
        ring-buffer-size-in-closed-state: 5
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 20s
        event-consumer-buffer-size: 10
        automatic-transition-from-open-to-half-open-enabled: true
        